### ISSUE TITLE
Search Autocomplete isn't displaying Smile Template

### ISSUE THREAD

**Issue by IbrahimS2** [breezefront/module-breeze-smile-elasticsuite#4]
I am using the very latest version of Magento, Smile & Breeze, I also checked from ElasticSearch response and it does include the necessary information to display the product image, price etc...

![image](https://github.com/user-attachments/assets/2d0a1797-7971-4f2f-970f-b3a58d31e797)

![image](https://github.com/user-attachments/assets/b38f6f26-4dc3-4b50-a483-b1d8fc5bb2fa)

**Comment by vovayatsyuk** [comment]
Did you install https://github.com/breezefront/module-breeze-smile-elasticsuite?

If yes, please provide an URL to to your site.

**Comment by IbrahimS2** [comment]
@vovayatsyuk https://onetimesecret.com/secret/d4fh7mxyk2uxed8vrgm575igjbrcz3l

**Comment by vovayatsyuk** [comment]
It looks like https://github.com/breezefront/module-breeze-smile-elasticsuite is not installed or activated. I don't see its js files.

**Comment by IbrahimS2** [comment]
@vovayatsyuk 
![image](https://github.com/user-attachments/assets/00fd6976-a256-4398-8624-c08ffb1c6950)

**Comment by vovayatsyuk** [comment]
I can't test it right now, but you can try the following workaround: 

Add `mixins` prop to the https://github.com/breezefront/module-breeze-smile-elasticsuite/blob/master/view/frontend/layout/breeze_default.xml#L28-L33:

```xml
<item name="smileEs.quickSearch" xsi:type="array">
    <item name="path" xsi:type="string">Swissup_BreezeSmileElasticsuite/js/quick-search</item>
    <item name="enabled" xsi:type="helper" helper="Swissup\Breeze\Helper\Config::isModuleEnabled">
        <param name="module">Smile_ElasticsuiteCore</param>
    </item>
    <item name="mixins" xsi:type="array">
        <item name="quickSearch" xsi:type="string">quickSearch</item>
    </item>
</item>
```

**Comment by IbrahimS2** [comment]
@vovayatsyuk That was it, I totally forgot about mixins in breeze :D

**Comment by vovayatsyuk** [comment]
Fixed in https://github.com/breezefront/module-breeze/commit/a41c81809376f98ba51d87136d61e34bcc25cdb1
