### ISSUE TITLE
"Show more" button doesn't work

### ISSUE THREAD

**Issue by ClivePatrick** [breezefront/module-breeze-smile-elasticsuite#6]
Nothing happens after clicking the "Show more" button when trying to expand categorical filters in layer navigation. 

After some digging, I believe the problem is caused inside the `loadAdditionalItems()` method of "Smile_ElasticsuiteCatalog/js/attribute-filter.js". The `$.get(url, data, success)` method is only being called with `url` and `success`, so the callback function ends up being confused for the payload data, and is undefined.

After adding `{}` after `this.ajaxLoadUrl` it seems to work perfectly fine.
```js
loadAdditionalItems: function (callback) {
  $.get(this.ajaxLoadUrl, {}, function (data) {
    this.items = data.map(this.addItemId.bind(this));
    this.hasMoreItems  = false;
    
    if (callback) {
      return callback();
    }
  }.bind(this));
},
```

It would be ideal to not have to modify "Smile_ElasticsuiteCatalog/js/attribute-filter.js". Thanks

**Comment by vovayatsyuk** [comment]
Thanks. Fixed in https://github.com/breezefront/module-breeze/commit/45fbcd82c8f0c7cda9c8f22f43c14e1d1cc70a09

**Comment by ClivePatrick** [comment]
Thank you for the quick response. That seems to work
