### ISSUE TITLE
Quicksearch Component Falls Back to module-breeze Version on Safari Devices

### ISSUE THREAD

**Issue by bensinca** [breezefront/module-breeze-smile-elasticsuite#7]
On Safari, the "quicksearch" component appears to default to the standard `vendor/swissup/module-breeze/view/frontend/web/js/components/quick-search.js` file rather than the expected `vendor/swissup/module-breeze-smile-elasticsuite/view/frontend/web/js/quick-search.js`.

### Steps to Reproduce:

Open the site on a Safari device.
Navigate to the search field and observe the loaded component for quicksearch.
Expected Behavior: The quicksearch component should load from module-breeze-smile-elasticsuite.

Actual Behavior: Safari falls back to the default module-breeze quicksearch component.

### Environment:

Magento version: 2.4.7-p3
Module-breeze-smile-elasticsuite version: 1.0.6
Breeze module: 2.17.16
smile/elasticsuite: 2.11.9
Browser: Safari

It appears that Safari may not be recognising or prioritising the customised quicksearch component from module-breeze-smile-elasticsuite.

Could this be related to any caching or fallback behaviour specific to Safari?

**Comment by vovayatsyuk** [comment]
Hi, could you please test if this fix helps? https://github.com/breezefront/module-breeze-smile-elasticsuite/commit/e29e99adf4a649bc904bd3d800fc2c7b9f5fadca

**Comment by bensinca** [comment]
hi @vovayatsyuk, that works!
